notifications:
  email: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH=$HOME/.yarn/bin:$PATH

language: node_js

node_js:
  - node

script:
  - yarn test
  - make build

cache:
  yarn: true
