version: "3"
services:

  # The HTTPS server and proxy on port 443
  webapp:
    image: quay.io/netzbegruenung/green-spider-webapp:latest
    restart: always
    ports:
    - "443:443"
    volumes:
      - $PWD:/workdir
      - $PWD/config/nginx/nginx_prod.conf:/etc/nginx/nginx.conf
      - $PWD/test-certs:/etc/letsencrypt/live/green-spider.netzbegruenung.de
      - $PWD/proxy-cache-prod:/var/cache/nginx

  api:
    image: quay.io/netzbegruenung/green-spider-api:latest
    restart: always
    ports:
    - 5000:5000
    environment:
      GCLOUD_DATASTORE_CREDENTIALS_PATH: /secrets/datastore-reader.json
    volumes:
      - $PWD/secrets:/secrets
    depends_on:
      - elasticsearch


  elasticsearch:
    image: elasticsearch:5.6-alpine
    environment:
      - cluster.name=green-spider
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
    - 9200:9200
    restart: always
    volumes:
      - $PWD/elasticsearch:/usr/share/elasticsearch/data

  indexer:
    image: quay.io/netzbegruenung/green-spider-indexer:latest
    volumes:
    - $PWD/secrets:/etc/indexer
    environment:
    - GCLOUD_DATASTORE_CREDENTIALS_PATH=/etc/indexer/datastore-reader.json
    restart: on-failure
