version: "3"
services:
  
  # proxy passing through webapp and api
  proxy:
    image: nginx:1.14-alpine
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/config/nginx/nginx_dev.conf:/etc/nginx/nginx.conf
      - ${PWD}/proxy-cache:/var/cache/nginx
    depends_on:
      - webapp
      - api

  # The webapp dev server on port 3000
  webapp:
    image: green-spider-webapp:dev
    build:
      context: .
      dockerfile: Dockerfile_node_dev
    command: yarn start
    ports:
    - "3000:3000"
    volumes:
      - ".:/workdir"
  
  api:
    image: quay.io/netzbegruenung/green-spider-api:latest
    ports:
    - 5000:5000
    environment:
      GCLOUD_DATASTORE_CREDENTIALS_PATH: /secrets/datastore-reader.json
    volumes:
      - "./secrets:/secrets"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:5.6-alpine
    environment:
      - cluster.name=green-spider
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
    - 9200:9200
    restart: always
    volumes:
      - $PWD/elasticsearch:/usr/share/elasticsearch/data

  indexer:
    image: quay.io/netzbegruenung/green-spider-indexer:latest
    volumes:
    - $PWD/secrets:/etc/indexer
    environment:
    - GCLOUD_DATASTORE_CREDENTIALS_PATH=/etc/indexer/datastore-reader.json
    restart: on-failure
